export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const REFRESHED_TOKEN = "REFRESHED_TOKEN";
export const TOKEN_REFRESH_FAIL = " TOKEN_REFRESH_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const USER_DELETED = "USER_DELETED"
export const USER_ADDED_SUCCESS = 'USER_ADDED_SUCCESS';
export const USER_ADDED_FAIL = 'USER_ADDED_FAIL';
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USERS_FETCH_SUCCESS = "USERS_FETCH_SUCCESS";
export const USER_CHANGED = "USER_CHANGED";
export const USER_SPOKE_FETCH_SUCCESS = "USER_SPOKE_FETCH_SUCCESS";
export const USER_ACTION_SUCCESS="USER_ACTION_SUCCESS";
export const FINISH_USER_ACTION="FINISH_USER_ACTION";
export const SET_USERS_OFFSET="SET_USERS_OFFSET";

export const PRODUCT_DELETED = "PRODUCT_DELETED";
export const PRODUCT_ADDED_SUCCESS = 'PRODUCT_ADDED_SUCCESS';
export const PRODUCT_ADDED_FAIL = 'PRODUCT_ADDED_FAIL';
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS";
export const PRODUCT_CHANGED = "PRODUCT_CHANGED";
export const PRODUCT_ACTION_SUCCESS="PRODUCT_ACTION_SUCCESS";
export const FINISH_PRODUCT_ACTION="FINISH_PRODUCT_ACTION";
export const SET_PRODUCTS_OFFSET="SET_PRODUCTS_OFFSET";
